import type { Mode, Profile } from "./types"

export const INTEREST_CATEGORIES: { label: string; items: string[] }[] = [
  { label: "Hobbies", items: ["music", "sports", "travel", "reading", "gaming", "cooking", "photography"] },
  { label: "Professional", items: ["tech", "finance", "healthcare", "education", "arts", "entrepreneurship"] },
  { label: "Lifestyle", items: ["fitness", "fashion", "food", "pets", "spirituality", "volunteering"] },
]

export const ALL_INTERESTS = INTEREST_CATEGORIES.flatMap((c) => c.items)

export const MODES: { id: Mode; label: string; emoji?: string }[] = [
  { id: "friendships", label: "Friendships" },
  { id: "dating", label: "Dating" },
  { id: "networking", label: "Networking" },
]

function photo(seed: string) {
  return `/placeholder.svg?height=600&width=450&query=portrait%20photo%20of%20${encodeURIComponent(seed)}`
}

export const SEED_PROFILES: Profile[] = [
  {
    id: "p1",
    name: "Amara",
    age: 27,
    gender: "female",
    city: "Accra",
    country: "Ghana",
    bio: "Lover of afrobeats, jollof debates, and weekend hikes. Looking for genuine connections.",
    interests: ["music", "travel", "food", "fitness"],
    mode: "dating",
    photos: [photo("smiling african woman outdoors"), photo("woman at cafe")],
    verified: true,
    online: true,
  },
  {
    id: "p2",
    name: "Kwame",
    age: 31,
    gender: "male",
    city: "Lagos",
    country: "Nigeria",
    bio: "Software engineer building for Africa. Always up for a good coffee chat about startups.",
    interests: ["tech", "entrepreneurship", "reading", "gaming"],
    mode: "networking",
    photos: [photo("african man in tech office"), photo("man smiling")],
    verified: true,
    online: false,
    industry: "Technology",
  },
  {
    id: "p3",
    name: "Sofia",
    age: 24,
    gender: "female",
    city: "Madrid",
    country: "Spain",
    bio: "Photographer chasing golden hour. Tell me your favourite city to shoot.",
    interests: ["photography", "travel", "arts", "fashion"],
    mode: "friendships",
    photos: [photo("young woman with camera"), photo("woman in city")],
    verified: false,
    online: true,
  },
  {
    id: "p4",
    name: "Yuki",
    age: 29,
    gender: "female",
    city: "Tokyo",
    country: "Japan",
    bio: "Designer & matcha enthusiast. Looking for creative friends around the world.",
    interests: ["arts", "food", "music", "fashion"],
    mode: "friendships",
    photos: [photo("japanese woman in studio"), photo("woman drinking tea")],
    verified: true,
    online: true,
  },
  {
    id: "p5",
    name: "Liam",
    age: 33,
    gender: "male",
    city: "London",
    country: "United Kingdom",
    bio: "Finance by day, marathon runner by dawn. Seeking someone to explore the world with.",
    interests: ["finance", "fitness", "travel", "sports"],
    mode: "dating",
    photos: [photo("man running in park"), photo("businessman portrait")],
    verified: false,
    online: false,
    industry: "Finance",
  },
  {
    id: "p6",
    name: "Priya",
    age: 26,
    gender: "female",
    city: "Mumbai",
    country: "India",
    bio: "Doctor with a soft spot for street food and stray cats. Let's be friends!",
    interests: ["healthcare", "food", "pets", "volunteering"],
    mode: "friendships",
    photos: [photo("indian woman doctor"), photo("woman with cat")],
    verified: true,
    online: true,
    industry: "Healthcare",
  },
  {
    id: "p7",
    name: "Mateo",
    age: 30,
    gender: "male",
    city: "Buenos Aires",
    country: "Argentina",
    bio: "Chef who believes food is love. Looking for my plus-one to taste the world.",
    interests: ["cooking", "food", "travel", "music"],
    mode: "dating",
    photos: [photo("chef in kitchen"), photo("man cooking")],
    verified: false,
    online: false,
  },
  {
    id: "p8",
    name: "Chioma",
    age: 28,
    gender: "female",
    city: "Abuja",
    country: "Nigeria",
    bio: "Founder building fintech for the diaspora. Always open to meeting fellow builders.",
    interests: ["entrepreneurship", "tech", "finance", "reading"],
    mode: "networking",
    photos: [photo("african businesswoman"), photo("woman presenting")],
    verified: true,
    online: true,
    industry: "Technology",
  },
  {
    id: "p9",
    name: "Noah",
    age: 25,
    gender: "male",
    city: "Berlin",
    country: "Germany",
    bio: "Music producer & vinyl collector. Looking for friends to hit festivals with.",
    interests: ["music", "arts", "gaming", "travel"],
    mode: "friendships",
    photos: [photo("man with headphones studio"), photo("dj at festival")],
    verified: false,
    online: true,
  },
  {
    id: "p10",
    name: "Elena",
    age: 32,
    gender: "female",
    city: "Athens",
    country: "Greece",
    bio: "Teacher and amateur sailor. Seeking deep conversations and seaside walks.",
    interests: ["education", "travel", "reading", "spirituality"],
    mode: "dating",
    photos: [photo("woman by the sea greece"), photo("teacher portrait")],
    verified: true,
    online: false,
    industry: "Education",
  },
  {
    id: "p11",
    name: "Daniel",
    age: 34,
    gender: "male",
    city: "Toronto",
    country: "Canada",
    bio: "Product manager and weekend climber. Let's grow our networks and maybe summit something.",
    interests: ["tech", "fitness", "sports", "entrepreneurship"],
    mode: "networking",
    photos: [photo("man climbing rock"), photo("professional headshot man")],
    verified: false,
    online: true,
    industry: "Technology",
  },
  {
    id: "p12",
    name: "Aisha",
    age: 23,
    gender: "female",
    city: "Nairobi",
    country: "Kenya",
    bio: "Fashion design student with big dreams. Looking for creative collaborators and friends.",
    interests: ["fashion", "arts", "photography", "music"],
    mode: "friendships",
    photos: [photo("kenyan fashion student"), photo("woman with colorful outfit")],
    verified: true,
    online: true,
  },
]

export function getSeedProfiles(): Profile[] {
  // deep clone to avoid mutation
  return SEED_PROFILES.map((p) => ({ ...p, photos: [...p.photos], interests: [...p.interests] }))
}
