/**
 * Admin1 (state/province/region) + major localities for all seeded countries
 * except Nigeria (see nigeria.ts). Complete admin1 lists; major cities per region.
 * Users can always type a custom city when not listed.
 */

export const ADMIN1_BY_COUNTRY: Record<string, { id: string; name: string }[]> = {
  nl: [
    { id: "nl-dr", name: "Drenthe" }, { id: "nl-fl", name: "Flevoland" }, { id: "nl-fr", name: "Friesland" },
    { id: "nl-ge", name: "Gelderland" }, { id: "nl-gr", name: "Groningen" }, { id: "nl-li", name: "Limburg" },
    { id: "nl-nb", name: "North Brabant" }, { id: "nl-nh", name: "North Holland" }, { id: "nl-ov", name: "Overijssel" },
    { id: "nl-ut", name: "Utrecht" }, { id: "nl-ze", name: "Zeeland" }, { id: "nl-zh", name: "South Holland" },
  ],
  cr: [
    { id: "cr-sj", name: "San José" }, { id: "cr-al", name: "Alajuela" }, { id: "cr-ca", name: "Cartago" },
    { id: "cr-he", name: "Heredia" }, { id: "cr-gu", name: "Guanacaste" }, { id: "cr-pu", name: "Puntarenas" },
    { id: "cr-li", name: "Limón" },
  ],
  ve: [
    { id: "ve-a", name: "Amazonas" }, { id: "ve-b", name: "Anzoátegui" }, { id: "ve-c", name: "Apure" },
    { id: "ve-d", name: "Aragua" }, { id: "ve-e", name: "Barinas" }, { id: "ve-f", name: "Bolívar" },
    { id: "ve-g", name: "Carabobo" }, { id: "ve-h", name: "Cojedes" }, { id: "ve-i", name: "Delta Amacuro" },
    { id: "ve-j", name: "Falcón" }, { id: "ve-k", name: "Guárico" }, { id: "ve-l", name: "Lara" },
    { id: "ve-m", name: "Mérida" }, { id: "ve-n", name: "Miranda" }, { id: "ve-o", name: "Monagas" },
    { id: "ve-p", name: "Nueva Esparta" }, { id: "ve-r", name: "Portuguesa" }, { id: "ve-s", name: "Sucre" },
    { id: "ve-t", name: "Táchira" }, { id: "ve-u", name: "Trujillo" }, { id: "ve-v", name: "Vargas" },
    { id: "ve-w", name: "Yaracuy" }, { id: "ve-x", name: "Zulia" }, { id: "ve-y", name: "Capital District" },
  ],
  to: [
    { id: "to-to", name: "Tongatapu" }, { id: "to-va", name: "Vava'u" }, { id: "to-ha", name: "Ha'apai" },
    { id: "to-eu", name: "'Eua" }, { id: "to-ni", name: "Niuas" },
  ],

  ar: [
    { id: "ar-caba", name: "Buenos Aires City" }, { id: "ar-ba", name: "Buenos Aires" }, { id: "ar-ct", name: "Catamarca" },
    { id: "ar-cc", name: "Chaco" }, { id: "ar-ch", name: "Chubut" }, { id: "ar-cb", name: "Córdoba" },
    { id: "ar-cr", name: "Corrientes" }, { id: "ar-er", name: "Entre Ríos" }, { id: "ar-fo", name: "Formosa" },
    { id: "ar-jy", name: "Jujuy" }, { id: "ar-lp", name: "La Pampa" }, { id: "ar-lr", name: "La Rioja" },
    { id: "ar-mz", name: "Mendoza" }, { id: "ar-mi", name: "Misiones" }, { id: "ar-nq", name: "Neuquén" },
    { id: "ar-rn", name: "Río Negro" }, { id: "ar-sa", name: "Salta" }, { id: "ar-sj", name: "San Juan" },
    { id: "ar-sl", name: "San Luis" }, { id: "ar-sc", name: "Santa Cruz" }, { id: "ar-sf", name: "Santa Fe" },
    { id: "ar-se", name: "Santiago del Estero" }, { id: "ar-tf", name: "Tierra del Fuego" }, { id: "ar-tu", name: "Tucumán" },
  ],
  au: [
    { id: "au-nsw", name: "New South Wales" }, { id: "au-vic", name: "Victoria" }, { id: "au-qld", name: "Queensland" },
    { id: "au-wa", name: "Western Australia" }, { id: "au-sa", name: "South Australia" }, { id: "au-tas", name: "Tasmania" },
    { id: "au-act", name: "Australian Capital Territory" }, { id: "au-nt", name: "Northern Territory" },
  ],
  br: [
    { id: "br-ac", name: "Acre" }, { id: "br-al", name: "Alagoas" }, { id: "br-ap", name: "Amapá" },
    { id: "br-am", name: "Amazonas" }, { id: "br-ba", name: "Bahia" }, { id: "br-ce", name: "Ceará" },
    { id: "br-df", name: "Federal District" }, { id: "br-es", name: "Espírito Santo" }, { id: "br-go", name: "Goiás" },
    { id: "br-ma", name: "Maranhão" }, { id: "br-mt", name: "Mato Grosso" }, { id: "br-ms", name: "Mato Grosso do Sul" },
    { id: "br-mg", name: "Minas Gerais" }, { id: "br-pa", name: "Pará" }, { id: "br-pb", name: "Paraíba" },
    { id: "br-pr", name: "Paraná" }, { id: "br-pe", name: "Pernambuco" }, { id: "br-pi", name: "Piauí" },
    { id: "br-rj", name: "Rio de Janeiro" }, { id: "br-rn", name: "Rio Grande do Norte" }, { id: "br-rs", name: "Rio Grande do Sul" },
    { id: "br-ro", name: "Rondônia" }, { id: "br-rr", name: "Roraima" }, { id: "br-sc", name: "Santa Catarina" },
    { id: "br-sp", name: "São Paulo" }, { id: "br-se", name: "Sergipe" }, { id: "br-to", name: "Tocantins" },
  ],
  ca: [
    { id: "ca-ab", name: "Alberta" }, { id: "ca-bc", name: "British Columbia" }, { id: "ca-mb", name: "Manitoba" },
    { id: "ca-nb", name: "New Brunswick" }, { id: "ca-nl", name: "Newfoundland and Labrador" }, { id: "ca-ns", name: "Nova Scotia" },
    { id: "ca-on", name: "Ontario" }, { id: "ca-pe", name: "Prince Edward Island" }, { id: "ca-qc", name: "Quebec" },
    { id: "ca-sk", name: "Saskatchewan" }, { id: "ca-nt", name: "Northwest Territories" }, { id: "ca-nu", name: "Nunavut" },
    { id: "ca-yt", name: "Yukon" },
  ],
  cl: [
    { id: "cl-ap", name: "Arica and Parinacota" }, { id: "cl-ta", name: "Tarapacá" }, { id: "cl-an", name: "Antofagasta" },
    { id: "cl-at", name: "Atacama" }, { id: "cl-co", name: "Coquimbo" }, { id: "cl-vs", name: "Valparaíso" },
    { id: "cl-rm", name: "Santiago Metropolitan" }, { id: "cl-li", name: "O'Higgins" }, { id: "cl-ml", name: "Maule" },
    { id: "cl-nb", name: "Ñuble" }, { id: "cl-bi", name: "Biobío" }, { id: "cl-ar", name: "Araucanía" },
    { id: "cl-lr", name: "Los Ríos" }, { id: "cl-ll", name: "Los Lagos" }, { id: "cl-ai", name: "Aysén" },
    { id: "cl-ma", name: "Magallanes" },
  ],
  cn: [
    { id: "cn-bj", name: "Beijing" }, { id: "cn-tj", name: "Tianjin" }, { id: "cn-he", name: "Hebei" },
    { id: "cn-sx", name: "Shanxi" }, { id: "cn-nm", name: "Inner Mongolia" }, { id: "cn-ln", name: "Liaoning" },
    { id: "cn-jl", name: "Jilin" }, { id: "cn-hl", name: "Heilongjiang" }, { id: "cn-sh", name: "Shanghai" },
    { id: "cn-js", name: "Jiangsu" }, { id: "cn-zj", name: "Zhejiang" }, { id: "cn-ah", name: "Anhui" },
    { id: "cn-fj", name: "Fujian" }, { id: "cn-jx", name: "Jiangxi" }, { id: "cn-sd", name: "Shandong" },
    { id: "cn-ha", name: "Henan" }, { id: "cn-hb", name: "Hubei" }, { id: "cn-hn", name: "Hunan" },
    { id: "cn-gd", name: "Guangdong" }, { id: "cn-gx", name: "Guangxi" }, { id: "cn-hi", name: "Hainan" },
    { id: "cn-cq", name: "Chongqing" }, { id: "cn-sc", name: "Sichuan" }, { id: "cn-gz", name: "Guizhou" },
    { id: "cn-yn", name: "Yunnan" }, { id: "cn-xz", name: "Tibet" }, { id: "cn-sn", name: "Shaanxi" },
    { id: "cn-gs", name: "Gansu" }, { id: "cn-qh", name: "Qinghai" }, { id: "cn-nx", name: "Ningxia" },
    { id: "cn-xj", name: "Xinjiang" }, { id: "cn-hk", name: "Hong Kong" }, { id: "cn-mo", name: "Macau" },
    { id: "cn-tw", name: "Taiwan" },
  ],
  co: [
    { id: "co-ama", name: "Amazonas" }, { id: "co-ant", name: "Antioquia" }, { id: "co-ara", name: "Arauca" },
    { id: "co-atl", name: "Atlántico" }, { id: "co-bol", name: "Bolívar" }, { id: "co-boy", name: "Boyacá" },
    { id: "co-cal", name: "Caldas" }, { id: "co-caq", name: "Caquetá" }, { id: "co-cas", name: "Casanare" },
    { id: "co-cau", name: "Cauca" }, { id: "co-ces", name: "Cesar" }, { id: "co-cho", name: "Chocó" },
    { id: "co-cor", name: "Córdoba" }, { id: "co-cun", name: "Cundinamarca" }, { id: "co-dc", name: "Bogotá D.C." },
    { id: "co-gua", name: "Guainía" }, { id: "co-guv", name: "Guaviare" }, { id: "co-hui", name: "Huila" },
    { id: "co-lag", name: "La Guajira" }, { id: "co-mag", name: "Magdalena" }, { id: "co-met", name: "Meta" },
    { id: "co-nar", name: "Nariño" }, { id: "co-nsa", name: "Norte de Santander" }, { id: "co-put", name: "Putumayo" },
    { id: "co-qui", name: "Quindío" }, { id: "co-ris", name: "Risaralda" }, { id: "co-sap", name: "San Andrés and Providencia" },
    { id: "co-san", name: "Santander" }, { id: "co-suc", name: "Sucre" }, { id: "co-tol", name: "Tolima" },
    { id: "co-vac", name: "Valle del Cauca" }, { id: "co-vau", name: "Vaupés" }, { id: "co-vid", name: "Vichada" },
  ],
  cu: [
    { id: "cu-hav", name: "Havana" }, { id: "cu-stg", name: "Santiago de Cuba" }, { id: "cu-cam", name: "Camagüey" },
    { id: "cu-hol", name: "Holguín" }, { id: "cu-mat", name: "Matanzas" }, { id: "cu-grm", name: "Granma" },
    { id: "cu-pri", name: "Pinar del Río" }, { id: "cu-vcl", name: "Villa Clara" }, { id: "cu-cfg", name: "Cienfuegos" },
    { id: "cu-ssp", name: "Sancti Spíritus" }, { id: "cu-ltu", name: "Las Tunas" }, { id: "cu-gtm", name: "Guantánamo" },
    { id: "cu-cfg2", name: "Ciego de Ávila" }, { id: "cu-may", name: "Mayabeque" }, { id: "cu-art", name: "Artemisa" },
    { id: "cu-ijv", name: "Isla de la Juventud" },
  ],
  de: [
    { id: "de-bw", name: "Baden-Württemberg" }, { id: "de-by", name: "Bavaria" }, { id: "de-be", name: "Berlin" },
    { id: "de-bb", name: "Brandenburg" }, { id: "de-hb", name: "Bremen" }, { id: "de-hh", name: "Hamburg" },
    { id: "de-he", name: "Hesse" }, { id: "de-mv", name: "Mecklenburg-Western Pomerania" }, { id: "de-ni", name: "Lower Saxony" },
    { id: "de-nw", name: "North Rhine-Westphalia" }, { id: "de-rp", name: "Rhineland-Palatinate" }, { id: "de-sl", name: "Saarland" },
    { id: "de-sn", name: "Saxony" }, { id: "de-st", name: "Saxony-Anhalt" }, { id: "de-sh", name: "Schleswig-Holstein" },
    { id: "de-th", name: "Thuringia" },
  ],
  eg: [
    { id: "eg-cai", name: "Cairo" }, { id: "eg-giz", name: "Giza" }, { id: "eg-alex", name: "Alexandria" },
    { id: "eg-dak", name: "Dakahlia" }, { id: "eg-red", name: "Red Sea" }, { id: "eg-behe", name: "Beheira" },
    { id: "eg-fay", name: "Faiyum" }, { id: "eg-ghar", name: "Gharbia" }, { id: "eg-ism", name: "Ismailia" },
    { id: "eg-menof", name: "Monufia" }, { id: "eg-min", name: "Minya" }, { id: "eg-qaly", name: "Qalyubia" },
    { id: "eg-nysa", name: "New Valley" }, { id: "eg-sue", name: "Suez" }, { id: "eg-asw", name: "Aswan" },
    { id: "eg-asy", name: "Asyut" }, { id: "eg-beni", name: "Beni Suef" }, { id: "eg-por", name: "Port Said" },
    { id: "eg-dam", name: "Damietta" }, { id: "eg-sha", name: "Sharqia" }, { id: "eg-sou", name: "South Sinai" },
    { id: "eg-kau", name: "Kafr El Sheikh" }, { id: "eg-mat", name: "Matrouh" }, { id: "eg-lux", name: "Luxor" },
    { id: "eg-qen", name: "Qena" }, { id: "eg-nor", name: "North Sinai" }, { id: "eg-soh", name: "Sohag" },
  ],
  es: [
    { id: "es-an", name: "Andalusia" }, { id: "es-ar", name: "Aragon" }, { id: "es-as", name: "Asturias" },
    { id: "es-ib", name: "Balearic Islands" }, { id: "es-cn", name: "Canary Islands" }, { id: "es-cb", name: "Cantabria" },
    { id: "es-cl", name: "Castile and León" }, { id: "es-cm", name: "Castilla-La Mancha" }, { id: "es-ct", name: "Catalonia" },
    { id: "es-ex", name: "Extremadura" }, { id: "es-ga", name: "Galicia" }, { id: "es-md", name: "Madrid" },
    { id: "es-mc", name: "Murcia" }, { id: "es-nc", name: "Navarre" }, { id: "es-pv", name: "Basque Country" },
    { id: "es-ri", name: "La Rioja" }, { id: "es-vc", name: "Valencia" }, { id: "es-ce", name: "Ceuta" },
    { id: "es-ml", name: "Melilla" },
  ],
  fj: [
    { id: "fj-cen", name: "Central" }, { id: "fj-eas", name: "Eastern" }, { id: "fj-nor", name: "Northern" },
    { id: "fj-wes", name: "Western" }, { id: "fj-rot", name: "Rotuma" },
  ],
  fr: [
    { id: "fr-ara", name: "Auvergne-Rhône-Alpes" }, { id: "fr-bfc", name: "Bourgogne-Franche-Comté" }, { id: "fr-bre", name: "Brittany" },
    { id: "fr-cvl", name: "Centre-Val de Loire" }, { id: "fr-cor", name: "Corsica" }, { id: "fr-ges", name: "Grand Est" },
    { id: "fr-hdf", name: "Hauts-de-France" }, { id: "fr-idf", name: "Île-de-France" }, { id: "fr-nor", name: "Normandy" },
    { id: "fr-naq", name: "Nouvelle-Aquitaine" }, { id: "fr-occ", name: "Occitanie" }, { id: "fr-pdl", name: "Pays de la Loire" },
    { id: "fr-pac", name: "Provence-Alpes-Côte d'Azur" },
  ],
  gb: [
    { id: "gb-eng", name: "England" }, { id: "gb-sct", name: "Scotland" }, { id: "gb-wls", name: "Wales" },
    { id: "gb-nir", name: "Northern Ireland" },
  ],
  gh: [
    { id: "gh-aha", name: "Ahafo" }, { id: "gh-ash", name: "Ashanti" }, { id: "gh-bon", name: "Bono" },
    { id: "gh-boe", name: "Bono East" }, { id: "gh-cen", name: "Central" }, { id: "gh-eas", name: "Eastern" },
    { id: "gh-ga", name: "Greater Accra" }, { id: "gh-ne", name: "North East" }, { id: "gh-nor", name: "Northern" },
    { id: "gh-oti", name: "Oti" }, { id: "gh-sav", name: "Savannah" }, { id: "gh-ue", name: "Upper East" },
    { id: "gh-uw", name: "Upper West" }, { id: "gh-vol", name: "Volta" }, { id: "gh-wes", name: "Western" },
    { id: "gh-wn", name: "Western North" },
  ],
  ht: [
    { id: "ht-ou", name: "Ouest" }, { id: "ht-no", name: "Nord" }, { id: "ht-ne", name: "Nord-Est" },
    { id: "ht-na", name: "Nord-Ouest" }, { id: "ht-ar", name: "Artibonite" }, { id: "ht-ce", name: "Centre" },
    { id: "ht-su", name: "Sud" }, { id: "ht-se", name: "Sud-Est" }, { id: "ht-gr", name: "Grand'Anse" },
    { id: "ht-ni", name: "Nippes" },
  ],
  id: [
    { id: "id-ac", name: "Aceh" }, { id: "id-su", name: "North Sumatra" }, { id: "id-sb", name: "West Sumatra" },
    { id: "id-ri", name: "Riau" }, { id: "id-kr", name: "Riau Islands" }, { id: "id-ja", name: "Jambi" },
    { id: "id-ss", name: "South Sumatra" }, { id: "id-be", name: "Bengkulu" }, { id: "id-la", name: "Lampung" },
    { id: "id-bb", name: "Bangka Belitung" }, { id: "id-jk", name: "Jakarta" }, { id: "id-jb", name: "West Java" },
    { id: "id-bt", name: "Banten" }, { id: "id-jt", name: "Central Java" }, { id: "id-yo", name: "Yogyakarta" },
    { id: "id-ji", name: "East Java" }, { id: "id-ba", name: "Bali" }, { id: "id-nb", name: "West Nusa Tenggara" },
    { id: "id-nt", name: "East Nusa Tenggara" }, { id: "id-kb", name: "West Kalimantan" }, { id: "id-kt", name: "Central Kalimantan" },
    { id: "id-ks", name: "South Kalimantan" }, { id: "id-ki", name: "East Kalimantan" }, { id: "id-ku", name: "North Kalimantan" },
    { id: "id-sa", name: "North Sulawesi" }, { id: "id-st", name: "Central Sulawesi" }, { id: "id-sn", name: "South Sulawesi" },
    { id: "id-sg", name: "Southeast Sulawesi" }, { id: "id-go", name: "Gorontalo" }, { id: "id-sr", name: "West Sulawesi" },
    { id: "id-ma", name: "Maluku" }, { id: "id-mu", name: "North Maluku" }, { id: "id-pa", name: "Papua" },
    { id: "id-pb", name: "West Papua" }, { id: "id-pe", name: "Highland Papua" }, { id: "id-ps", name: "South Papua" },
    { id: "id-pt", name: "Central Papua" }, { id: "id-sw", name: "Southwest Papua" },
  ],
  in: [
    { id: "in-an", name: "Andaman and Nicobar" }, { id: "in-ap", name: "Andhra Pradesh" }, { id: "in-ar", name: "Arunachal Pradesh" },
    { id: "in-as", name: "Assam" }, { id: "in-br", name: "Bihar" }, { id: "in-ch", name: "Chandigarh" },
    { id: "in-ct", name: "Chhattisgarh" }, { id: "in-dh", name: "Dadra and Nagar Haveli and Daman and Diu" }, { id: "in-dl", name: "Delhi" },
    { id: "in-ga", name: "Goa" }, { id: "in-gj", name: "Gujarat" }, { id: "in-hr", name: "Haryana" },
    { id: "in-hp", name: "Himachal Pradesh" }, { id: "in-jk", name: "Jammu and Kashmir" }, { id: "in-jh", name: "Jharkhand" },
    { id: "in-ka", name: "Karnataka" }, { id: "in-kl", name: "Kerala" }, { id: "in-la", name: "Ladakh" },
    { id: "in-ld", name: "Lakshadweep" }, { id: "in-mp", name: "Madhya Pradesh" }, { id: "in-mh", name: "Maharashtra" },
    { id: "in-mn", name: "Manipur" }, { id: "in-ml", name: "Meghalaya" }, { id: "in-mz", name: "Mizoram" },
    { id: "in-nl", name: "Nagaland" }, { id: "in-od", name: "Odisha" }, { id: "in-py", name: "Puducherry" },
    { id: "in-pb", name: "Punjab" }, { id: "in-rj", name: "Rajasthan" }, { id: "in-sk", name: "Sikkim" },
    { id: "in-tn", name: "Tamil Nadu" }, { id: "in-tg", name: "Telangana" }, { id: "in-tr", name: "Tripura" },
    { id: "in-up", name: "Uttar Pradesh" }, { id: "in-uk", name: "Uttarakhand" }, { id: "in-wb", name: "West Bengal" },
  ],
  it: [
    { id: "it-abr", name: "Abruzzo" }, { id: "it-bas", name: "Basilicata" }, { id: "it-cal", name: "Calabria" },
    { id: "it-cam", name: "Campania" }, { id: "it-emr", name: "Emilia-Romagna" }, { id: "it-fvg", name: "Friuli-Venezia Giulia" },
    { id: "it-laz", name: "Lazio" }, { id: "it-lig", name: "Liguria" }, { id: "it-lom", name: "Lombardy" },
    { id: "it-mar", name: "Marche" }, { id: "it-mol", name: "Molise" }, { id: "it-pie", name: "Piedmont" },
    { id: "it-pug", name: "Apulia" }, { id: "it-sar", name: "Sardinia" }, { id: "it-sic", name: "Sicily" },
    { id: "it-tus", name: "Tuscany" }, { id: "it-taa", name: "Trentino-South Tyrol" }, { id: "it-umb", name: "Umbria" },
    { id: "it-vda", name: "Aosta Valley" }, { id: "it-ven", name: "Veneto" },
  ],
  jm: [
    { id: "jm-ki", name: "Kingston" }, { id: "jm-st", name: "Saint Andrew" }, { id: "jm-sy", name: "Saint James" },
    { id: "jm-cl", name: "Clarendon" }, { id: "jm-stc", name: "Saint Catherine" }, { id: "jm-ma", name: "Manchester" },
    { id: "jm-stt", name: "Saint Thomas" }, { id: "jm-po", name: "Portland" }, { id: "jm-tre", name: "Trelawny" },
    { id: "jm-stn", name: "Saint Ann" }, { id: "jm-ste", name: "Saint Elizabeth" }, { id: "jm-wes", name: "Westmoreland" },
    { id: "jm-han", name: "Hanover" }, { id: "jm-stm", name: "Saint Mary" },
  ],
  jp: [
    { id: "jp-hokkaido", name: "Hokkaido" }, { id: "jp-aomori", name: "Aomori" }, { id: "jp-iwate", name: "Iwate" },
    { id: "jp-miyagi", name: "Miyagi" }, { id: "jp-akita", name: "Akita" }, { id: "jp-yamagata", name: "Yamagata" },
    { id: "jp-fukushima", name: "Fukushima" }, { id: "jp-ibaraki", name: "Ibaraki" }, { id: "jp-tochigi", name: "Tochigi" },
    { id: "jp-gunma", name: "Gunma" }, { id: "jp-saitama", name: "Saitama" }, { id: "jp-chiba", name: "Chiba" },
    { id: "jp-tokyo", name: "Tokyo" }, { id: "jp-kanagawa", name: "Kanagawa" }, { id: "jp-niigata", name: "Niigata" },
    { id: "jp-toyama", name: "Toyama" }, { id: "jp-ishikawa", name: "Ishikawa" }, { id: "jp-fukui", name: "Fukui" },
    { id: "jp-yamanashi", name: "Yamanashi" }, { id: "jp-nagano", name: "Nagano" }, { id: "jp-gifu", name: "Gifu" },
    { id: "jp-shizuoka", name: "Shizuoka" }, { id: "jp-aichi", name: "Aichi" }, { id: "jp-mie", name: "Mie" },
    { id: "jp-shiga", name: "Shiga" }, { id: "jp-kyoto", name: "Kyoto" }, { id: "jp-osaka", name: "Osaka" },
    { id: "jp-hyogo", name: "Hyogo" }, { id: "jp-nara", name: "Nara" }, { id: "jp-wakayama", name: "Wakayama" },
    { id: "jp-tottori", name: "Tottori" }, { id: "jp-shimane", name: "Shimane" }, { id: "jp-okayama", name: "Okayama" },
    { id: "jp-hiroshima", name: "Hiroshima" }, { id: "jp-yamaguchi", name: "Yamaguchi" }, { id: "jp-tokushima", name: "Tokushima" },
    { id: "jp-kagawa", name: "Kagawa" }, { id: "jp-ehime", name: "Ehime" }, { id: "jp-kochi", name: "Kochi" },
    { id: "jp-fukuoka", name: "Fukuoka" }, { id: "jp-saga", name: "Saga" }, { id: "jp-nagasaki", name: "Nagasaki" },
    { id: "jp-kumamoto", name: "Kumamoto" }, { id: "jp-oita", name: "Oita" }, { id: "jp-miyazaki", name: "Miyazaki" },
    { id: "jp-kagoshima", name: "Kagoshima" }, { id: "jp-okinawa", name: "Okinawa" },
  ],
  ke: [
    { id: "ke-mombasa", name: "Mombasa" }, { id: "ke-kwale", name: "Kwale" }, { id: "ke-kilifi", name: "Kilifi" },
    { id: "ke-tana-river", name: "Tana River" }, { id: "ke-lamu", name: "Lamu" }, { id: "ke-taita-taveta", name: "Taita-Taveta" },
    { id: "ke-garissa", name: "Garissa" }, { id: "ke-wajir", name: "Wajir" }, { id: "ke-mandera", name: "Mandera" },
    { id: "ke-marsabit", name: "Marsabit" }, { id: "ke-isiolo", name: "Isiolo" }, { id: "ke-meru", name: "Meru" },
    { id: "ke-tharaka-nithi", name: "Tharaka-Nithi" }, { id: "ke-embu", name: "Embu" }, { id: "ke-kitui", name: "Kitui" },
    { id: "ke-machakos", name: "Machakos" }, { id: "ke-makueni", name: "Makueni" }, { id: "ke-nyandarua", name: "Nyandarua" },
    { id: "ke-nyeri", name: "Nyeri" }, { id: "ke-kirinyaga", name: "Kirinyaga" }, { id: "ke-muranga", name: "Murang'a" },
    { id: "ke-kiambu", name: "Kiambu" }, { id: "ke-turkana", name: "Turkana" }, { id: "ke-west-pokot", name: "West Pokot" },
    { id: "ke-samburu", name: "Samburu" }, { id: "ke-trans-nzoia", name: "Trans-Nzoia" }, { id: "ke-uasin-gishu", name: "Uasin Gishu" },
    { id: "ke-elgeyo-marakwet", name: "Elgeyo-Marakwet" }, { id: "ke-nandi", name: "Nandi" }, { id: "ke-baringo", name: "Baringo" },
    { id: "ke-laikipia", name: "Laikipia" }, { id: "ke-nakuru", name: "Nakuru" }, { id: "ke-narok", name: "Narok" },
    { id: "ke-kajiado", name: "Kajiado" }, { id: "ke-kericho", name: "Kericho" }, { id: "ke-bomet", name: "Bomet" },
    { id: "ke-kakamega", name: "Kakamega" }, { id: "ke-vihiga", name: "Vihiga" }, { id: "ke-bungoma", name: "Bungoma" },
    { id: "ke-busia", name: "Busia" }, { id: "ke-siaya", name: "Siaya" }, { id: "ke-kisumu", name: "Kisumu" },
    { id: "ke-homa-bay", name: "Homa Bay" }, { id: "ke-migori", name: "Migori" }, { id: "ke-kisii", name: "Kisii" },
    { id: "ke-nyamira", name: "Nyamira" }, { id: "ke-nairobi", name: "Nairobi" },
  ],
  kr: [
    { id: "kr-su", name: "Seoul" }, { id: "kr-bs", name: "Busan" }, { id: "kr-dg", name: "Daegu" },
    { id: "kr-ic", name: "Incheon" }, { id: "kr-gj", name: "Gwangju" }, { id: "kr-dj", name: "Daejeon" },
    { id: "kr-us", name: "Ulsan" }, { id: "kr-sj", name: "Sejong" }, { id: "kr-gg", name: "Gyeonggi" },
    { id: "kr-gw", name: "Gangwon" }, { id: "kr-cb", name: "North Chungcheong" }, { id: "kr-cn", name: "South Chungcheong" },
    { id: "kr-jb", name: "North Jeolla" }, { id: "kr-jn", name: "South Jeolla" }, { id: "kr-gb", name: "North Gyeongsang" },
    { id: "kr-gn", name: "South Gyeongsang" }, { id: "kr-jj", name: "Jeju" },
  ],
  ma: [
    { id: "ma-tn", name: "Tanger-Tetouan-Al Hoceima" }, { id: "ma-or", name: "Oriental" }, { id: "ma-fm", name: "Fès-Meknès" },
    { id: "ma-rs", name: "Rabat-Salé-Kénitra" }, { id: "ma-bs", name: "Béni Mellal-Khénifra" }, { id: "ma-cs", name: "Casablanca-Settat" },
    { id: "ma-ms", name: "Marrakech-Safi" }, { id: "ma-dt", name: "Drâa-Tafilalet" }, { id: "ma-sm", name: "Souss-Massa" },
    { id: "ma-gu", name: "Guelmim-Oued Noun" }, { id: "ma-la", name: "Laâyoune-Sakia El Hamra" }, { id: "ma-da", name: "Dakhla-Oued Ed-Dahab" },
  ],
  mx: [
    { id: "mx-agu", name: "Aguascalientes" }, { id: "mx-bcn", name: "Baja California" }, { id: "mx-bcs", name: "Baja California Sur" },
    { id: "mx-cam", name: "Campeche" }, { id: "mx-chp", name: "Chiapas" }, { id: "mx-chh", name: "Chihuahua" },
    { id: "mx-cmx", name: "Mexico City" }, { id: "mx-coa", name: "Coahuila" }, { id: "mx-col", name: "Colima" },
    { id: "mx-dur", name: "Durango" }, { id: "mx-gua", name: "Guanajuato" }, { id: "mx-gro", name: "Guerrero" },
    { id: "mx-hid", name: "Hidalgo" }, { id: "mx-jal", name: "Jalisco" }, { id: "mx-mex", name: "State of Mexico" },
    { id: "mx-mic", name: "Michoacán" }, { id: "mx-mor", name: "Morelos" }, { id: "mx-nay", name: "Nayarit" },
    { id: "mx-nle", name: "Nuevo León" }, { id: "mx-oax", name: "Oaxaca" }, { id: "mx-pue", name: "Puebla" },
    { id: "mx-que", name: "Querétaro" }, { id: "mx-roo", name: "Quintana Roo" }, { id: "mx-slp", name: "San Luis Potosí" },
    { id: "mx-sin", name: "Sinaloa" }, { id: "mx-son", name: "Sonora" }, { id: "mx-tab", name: "Tabasco" },
    { id: "mx-tam", name: "Tamaulipas" }, { id: "mx-tla", name: "Tlaxcala" }, { id: "mx-ver", name: "Veracruz" },
    { id: "mx-yuc", name: "Yucatán" }, { id: "mx-zac", name: "Zacatecas" },
  ],
  nz: [
    { id: "nz-auk", name: "Auckland" }, { id: "nz-wgn", name: "Wellington" }, { id: "nz-can", name: "Canterbury" },
    { id: "nz-waik", name: "Waikato" }, { id: "nz-bay", name: "Bay of Plenty" }, { id: "nz-ota", name: "Otago" },
    { id: "nz-man", name: "Manawatū-Whanganui" }, { id: "nz-haw", name: "Hawke's Bay" }, { id: "nz-tki", name: "Taranaki" },
    { id: "nz-ntl", name: "Northland" }, { id: "nz-stl", name: "Southland" }, { id: "nz-nsl", name: "Nelson" },
    { id: "nz-mar", name: "Marlborough" }, { id: "nz-tas", name: "Tasman" }, { id: "nz-wtc", name: "West Coast" },
    { id: "nz-gis", name: "Gisborne" },
  ],
  pe: [
    { id: "pe-ama", name: "Amazonas" }, { id: "pe-anc", name: "Ancash" }, { id: "pe-apu", name: "Apurímac" },
    { id: "pe-are", name: "Arequipa" }, { id: "pe-aya", name: "Ayacucho" }, { id: "pe-caj", name: "Cajamarca" },
    { id: "pe-cal", name: "Callao" }, { id: "pe-cus", name: "Cusco" }, { id: "pe-huv", name: "Huancavelica" },
    { id: "pe-huc", name: "Huánuco" }, { id: "pe-ica", name: "Ica" }, { id: "pe-jun", name: "Junín" },
    { id: "pe-lal", name: "La Libertad" }, { id: "pe-lam", name: "Lambayeque" }, { id: "pe-lim", name: "Lima" },
    { id: "pe-lor", name: "Loreto" }, { id: "pe-mdd", name: "Madre de Dios" }, { id: "pe-moq", name: "Moquegua" },
    { id: "pe-pas", name: "Pasco" }, { id: "pe-piu", name: "Piura" }, { id: "pe-pun", name: "Puno" },
    { id: "pe-sam", name: "San Martín" }, { id: "pe-tac", name: "Tacna" }, { id: "pe-tum", name: "Tumbes" },
    { id: "pe-uca", name: "Ucayali" },
  ],
  pg: [
    { id: "pg-ncd", name: "National Capital District" }, { id: "pg-mop", name: "Morobe" }, { id: "pg-ehp", name: "Eastern Highlands" },
    { id: "pg-whp", name: "Western Highlands" }, { id: "pg-mad", name: "Madang" }, { id: "pg-ebp", name: "East New Britain" },
    { id: "pg-wbp", name: "West New Britain" }, { id: "pg-shl", name: "Southern Highlands" }, { id: "pg-eng", name: "Enga" },
    { id: "pg-sim", name: "Simbu" }, { id: "pg-oro", name: "Northern" }, { id: "pg-mil", name: "Milne Bay" },
    { id: "pg-gul", name: "Gulf" }, { id: "pg-wes", name: "Western" }, { id: "pg-san", name: "Sandaun" },
    { id: "pg-esp", name: "East Sepik" }, { id: "pg-man", name: "Manus" }, { id: "pg-nni", name: "New Ireland" },
    { id: "pg-bgl", name: "Bougainville" }, { id: "pg-jiw", name: "Jiwaka" }, { id: "pg-hec", name: "Hela" },
  ],
  pl: [
    { id: "pl-ds", name: "Lower Silesian" }, { id: "pl-kp", name: "Kuyavian-Pomeranian" }, { id: "pl-lu", name: "Lublin" },
    { id: "pl-lb", name: "Lubusz" }, { id: "pl-ld", name: "Łódź" }, { id: "pl-mp", name: "Lesser Poland" },
    { id: "pl-mz", name: "Masovian" }, { id: "pl-op", name: "Opole" }, { id: "pl-pk", name: "Subcarpathian" },
    { id: "pl-pd", name: "Podlaskie" }, { id: "pl-pm", name: "Pomeranian" }, { id: "pl-sl", name: "Silesian" },
    { id: "pl-sk", name: "Holy Cross" }, { id: "pl-wn", name: "Warmian-Masurian" }, { id: "pl-wp", name: "Greater Poland" },
    { id: "pl-zp", name: "West Pomeranian" },
  ],
  sa: [
    { id: "sa-ri", name: "Riyadh" }, { id: "sa-mk", name: "Makkah" }, { id: "sa-md", name: "Madinah" },
    { id: "sa-qa", name: "Qassim" }, { id: "sa-ea", name: "Eastern Province" }, { id: "sa-as", name: "Asir" },
    { id: "sa-tb", name: "Tabuk" }, { id: "sa-ha", name: "Hail" }, { id: "sa-nb", name: "Northern Borders" },
    { id: "sa-jz", name: "Jazan" }, { id: "sa-nj", name: "Najran" }, { id: "sa-ba", name: "Al Bahah" },
    { id: "sa-jf", name: "Al Jawf" },
  ],
  sb: [
    { id: "sb-cap", name: "Capital" }, { id: "sb-gua", name: "Guadalcanal" }, { id: "sb-mal", name: "Malaita" },
    { id: "sb-wes", name: "Western" }, { id: "sb-cho", name: "Choiseul" }, { id: "sb-mak", name: "Makira-Ulawa" },
    { id: "sb-tem", name: "Temotu" }, { id: "sb-isa", name: "Isabel" }, { id: "sb-cen", name: "Central" },
    { id: "sb-ren", name: "Rennell and Bellona" },
  ],
  us: [
    { id: "us-al", name: "Alabama" }, { id: "us-ak", name: "Alaska" }, { id: "us-az", name: "Arizona" },
    { id: "us-ar", name: "Arkansas" }, { id: "us-ca", name: "California" }, { id: "us-co", name: "Colorado" },
    { id: "us-ct", name: "Connecticut" }, { id: "us-de", name: "Delaware" }, { id: "us-dc", name: "District of Columbia" },
    { id: "us-fl", name: "Florida" }, { id: "us-ga", name: "Georgia" }, { id: "us-hi", name: "Hawaii" },
    { id: "us-id", name: "Idaho" }, { id: "us-il", name: "Illinois" }, { id: "us-in", name: "Indiana" },
    { id: "us-ia", name: "Iowa" }, { id: "us-ks", name: "Kansas" }, { id: "us-ky", name: "Kentucky" },
    { id: "us-la", name: "Louisiana" }, { id: "us-me", name: "Maine" }, { id: "us-md", name: "Maryland" },
    { id: "us-ma", name: "Massachusetts" }, { id: "us-mi", name: "Michigan" }, { id: "us-mn", name: "Minnesota" },
    { id: "us-ms", name: "Mississippi" }, { id: "us-mo", name: "Missouri" }, { id: "us-mt", name: "Montana" },
    { id: "us-ne", name: "Nebraska" }, { id: "us-nv", name: "Nevada" }, { id: "us-nh", name: "New Hampshire" },
    { id: "us-nj", name: "New Jersey" }, { id: "us-nm", name: "New Mexico" }, { id: "us-ny", name: "New York" },
    { id: "us-nc", name: "North Carolina" }, { id: "us-nd", name: "North Dakota" }, { id: "us-oh", name: "Ohio" },
    { id: "us-ok", name: "Oklahoma" }, { id: "us-or", name: "Oregon" }, { id: "us-pa", name: "Pennsylvania" },
    { id: "us-ri", name: "Rhode Island" }, { id: "us-sc", name: "South Carolina" }, { id: "us-sd", name: "South Dakota" },
    { id: "us-tn", name: "Tennessee" }, { id: "us-tx", name: "Texas" }, { id: "us-ut", name: "Utah" },
    { id: "us-vt", name: "Vermont" }, { id: "us-va", name: "Virginia" }, { id: "us-wa", name: "Washington" },
    { id: "us-wv", name: "West Virginia" }, { id: "us-wi", name: "Wisconsin" }, { id: "us-wy", name: "Wyoming" },
  ],
  ws: [
    { id: "ws-tu", name: "Tuamasaga" }, { id: "ws-aa", name: "A'ana" }, { id: "ws-at", name: "Aiga-i-le-Tai" },
    { id: "ws-fa", name: "Fa'asaleleaga" }, { id: "ws-ga", name: "Gaga'emauga" }, { id: "ws-gf", name: "Gaga'ifomauga" },
    { id: "ws-pa", name: "Palauli" }, { id: "ws-sa", name: "Satupa'itea" }, { id: "ws-va", name: "Va'a-o-Fonoti" },
    { id: "ws-vs", name: "Vaisigano" }, { id: "ws-al", name: "Aloa" },
  ],
  za: [
    { id: "za-ec", name: "Eastern Cape" }, { id: "za-fs", name: "Free State" }, { id: "za-gp", name: "Gauteng" },
    { id: "za-kzn", name: "KwaZulu-Natal" }, { id: "za-lp", name: "Limpopo" }, { id: "za-mp", name: "Mpumalanga" },
    { id: "za-nw", name: "North West" }, { id: "za-nc", name: "Northern Cape" }, { id: "za-wc", name: "Western Cape" },
  ],
}

/** Major cities / towns keyed by admin1 id */
export const LOCALITIES_BY_ADMIN1: Record<string, string[]> = {
  "nl-nh": ["Amsterdam", "Haarlem", "Hilversum"],
  "nl-zh": ["Rotterdam", "The Hague", "Leiden", "Delft"],
  "nl-ut": ["Utrecht"],
  "nl-ge": ["Arnhem", "Nijmegen"],
  "nl-nb": ["Eindhoven", "Tilburg", "Breda"],
  "cr-sj": ["San José", "Escazú", "Desamparados"],
  "cr-al": ["Alajuela"],
  "cr-li": ["Limón", "Puerto Viejo"],
  "cr-gu": ["Liberia", "Tamarindo"],
  "ve-y": ["Caracas"],
  "ve-x": ["Maracaibo"],
  "ve-g": ["Valencia"],
  "ve-n": ["Los Teques", "Petare"],
  "ve-b": ["Barcelona", "Puerto La Cruz"],
  "to-to": ["Nuku'alofa", "Haveluloto"],
  "to-va": ["Neiafu"],
  "ar-ba": ["La Plata", "Mar del Plata", "Bahía Blanca"],
  "ar-caba": ["Buenos Aires", "Palermo", "Recoleta"],
  "ar-cb": ["Córdoba"],
  "ar-mz": ["Mendoza"],
  "ar-sf": ["Rosario", "Santa Fe"],
  "ar-tu": ["San Miguel de Tucumán"],
  "au-act": ["Canberra"],
  "au-nsw": ["Sydney", "Newcastle", "Wollongong", "Parramatta"],
  "au-nt": ["Darwin"],
  "au-qld": ["Brisbane", "Gold Coast", "Cairns", "Townsville"],
  "au-sa": ["Adelaide"],
  "au-tas": ["Hobart", "Launceston"],
  "au-vic": ["Melbourne", "Geelong", "Ballarat"],
  "au-wa": ["Perth", "Fremantle"],
  "br-am": ["Manaus"],
  "br-ba": ["Salvador", "Feira de Santana"],
  "br-ce": ["Fortaleza"],
  "br-df": ["Brasília"],
  "br-mg": ["Belo Horizonte", "Uberlândia"],
  "br-pe": ["Recife"],
  "br-pr": ["Curitiba"],
  "br-rj": ["Rio de Janeiro", "Niterói"],
  "br-rs": ["Porto Alegre"],
  "br-sp": ["São Paulo", "Campinas", "Santos", "Guarulhos"],
  "ca-ab": ["Calgary", "Edmonton"],
  "ca-bc": ["Vancouver", "Victoria", "Surrey", "Burnaby"],
  "ca-mb": ["Winnipeg"],
  "ca-ns": ["Halifax"],
  "ca-on": ["Toronto", "Ottawa", "Mississauga", "Hamilton", "London"],
  "ca-qc": ["Montreal", "Quebec City", "Laval"],
  "ca-sk": ["Saskatoon", "Regina"],
  "cl-an": ["Antofagasta"],
  "cl-bi": ["Concepción"],
  "cl-rm": ["Santiago", "Puente Alto", "Maipú"],
  "cl-vs": ["Valparaíso", "Viña del Mar"],
  "cn-bj": ["Beijing"],
  "cn-cq": ["Chongqing"],
  "cn-gd": ["Guangzhou", "Shenzhen", "Dongguan", "Foshan"],
  "cn-hb": ["Wuhan"],
  "cn-hk": ["Hong Kong"],
  "cn-js": ["Nanjing", "Suzhou", "Wuxi"],
  "cn-sc": ["Chengdu"],
  "cn-sd": ["Jinan", "Qingdao"],
  "cn-sh": ["Shanghai"],
  "cn-tj": ["Tianjin"],
  "cn-zj": ["Hangzhou", "Ningbo", "Wenzhou"],
  "co-ant": ["Medellín", "Envigado"],
  "co-atl": ["Barranquilla"],
  "co-bol": ["Cartagena"],
  "co-dc": ["Bogotá"],
  "co-san": ["Bucaramanga"],
  "co-vac": ["Cali", "Palmira"],
  "cu-hav": ["Havana", "Old Havana", "Vedado"],
  "cu-stg": ["Santiago de Cuba"],
  "de-be": ["Berlin"],
  "de-bw": ["Stuttgart", "Mannheim", "Karlsruhe"],
  "de-by": ["Munich", "Nuremberg", "Augsburg"],
  "de-he": ["Frankfurt", "Wiesbaden"],
  "de-hh": ["Hamburg"],
  "de-ni": ["Hanover", "Braunschweig"],
  "de-nw": ["Cologne", "Düsseldorf", "Dortmund", "Essen", "Bonn"],
  "de-sn": ["Dresden", "Leipzig"],
  "eg-alex": ["Alexandria", "Borg El Arab"],
  "eg-asw": ["Aswan"],
  "eg-cai": ["Cairo", "Helwan", "Nasr City", "Heliopolis", "Maadi"],
  "eg-giz": ["Giza", "6th of October", "Sheikh Zayed", "Dokki"],
  "eg-lux": ["Luxor"],
  "eg-por": ["Port Said"],
  "eg-sha": ["Zagazig", "10th of Ramadan"],
  "eg-sue": ["Suez"],
  "es-an": ["Seville", "Málaga", "Granada", "Córdoba"],
  "es-cn": ["Las Palmas", "Santa Cruz de Tenerife"],
  "es-ct": ["Barcelona", "Girona", "Tarragona"],
  "es-ga": ["Vigo", "A Coruña"],
  "es-ib": ["Palma"],
  "es-md": ["Madrid"],
  "es-pv": ["Bilbao", "San Sebastián"],
  "es-vc": ["Valencia", "Alicante"],
  "fj-cen": ["Suva", "Nausori"],
  "fj-wes": ["Nadi", "Lautoka"],
  "fr-ara": ["Lyon", "Grenoble", "Saint-Étienne", "Clermont-Ferrand"],
  "fr-bre": ["Rennes", "Brest"],
  "fr-ges": ["Strasbourg", "Reims", "Metz"],
  "fr-hdf": ["Lille", "Amiens"],
  "fr-idf": ["Paris", "Versailles", "Boulogne-Billancourt", "Saint-Denis"],
  "fr-naq": ["Bordeaux", "Limoges", "Poitiers"],
  "fr-nor": ["Rouen", "Le Havre", "Caen"],
  "fr-occ": ["Toulouse", "Montpellier", "Nîmes"],
  "fr-pac": ["Marseille", "Nice", "Toulon", "Aix-en-Provence"],
  "fr-pdl": ["Nantes", "Angers", "Le Mans"],
  "gb-eng": ["London", "Manchester", "Birmingham", "Leeds", "Liverpool", "Bristol", "Sheffield", "Newcastle", "Nottingham", "Leicester"],
  "gb-nir": ["Belfast", "Derry"],
  "gb-sct": ["Edinburgh", "Glasgow", "Aberdeen", "Dundee"],
  "gb-wls": ["Cardiff", "Swansea", "Newport"],
  "gh-ash": ["Kumasi", "Obuasi", "Ejisu"],
  "gh-bon": ["Sunyani"],
  "gh-cen": ["Cape Coast", "Winneba", "Kasoa"],
  "gh-eas": ["Koforidua", "Nkawkaw"],
  "gh-ga": ["Accra", "Tema", "Madina", "Adenta", "Teshie", "Nungua", "Dansoman"],
  "gh-nor": ["Tamale", "Yendi"],
  "gh-ue": ["Bolgatanga"],
  "gh-uw": ["Wa"],
  "gh-vol": ["Ho", "Keta"],
  "gh-wes": ["Takoradi", "Sekondi", "Tarkwa"],
  "ht-no": ["Cap-Haïtien"],
  "ht-ou": ["Port-au-Prince", "Pétion-Ville", "Carrefour", "Delmas"],
  "id-ba": ["Denpasar", "Ubud", "Singaraja"],
  "id-bt": ["Tangerang", "South Tangerang", "Serang"],
  "id-jb": ["Bandung", "Bekasi", "Depok", "Bogor"],
  "id-ji": ["Surabaya", "Malang", "Sidoarjo"],
  "id-jk": ["Jakarta", "Central Jakarta", "South Jakarta", "West Jakarta", "East Jakarta", "North Jakarta"],
  "id-sn": ["Makassar"],
  "id-su": ["Medan"],
  "id-yo": ["Yogyakarta"],
  "in-ap": ["Visakhapatnam", "Vijayawada"],
  "in-as": ["Guwahati"],
  "in-br": ["Patna"],
  "in-dl": ["New Delhi", "Delhi"],
  "in-gj": ["Ahmedabad", "Surat", "Vadodara", "Rajkot"],
  "in-hr": ["Gurugram", "Faridabad"],
  "in-ka": ["Bengaluru", "Mysuru", "Mangaluru"],
  "in-kl": ["Thiruvananthapuram", "Kochi", "Kozhikode"],
  "in-mh": ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik"],
  "in-mp": ["Bhopal", "Indore"],
  "in-od": ["Bhubaneswar", "Cuttack"],
  "in-pb": ["Chandigarh", "Ludhiana", "Amritsar"],
  "in-rj": ["Jaipur", "Jodhpur", "Udaipur"],
  "in-tg": ["Hyderabad", "Warangal"],
  "in-tn": ["Chennai", "Coimbatore", "Madurai"],
  "in-up": ["Lucknow", "Kanpur", "Varanasi", "Noida", "Agra"],
  "in-wb": ["Kolkata", "Howrah", "Siliguri"],
  "it-cam": ["Naples", "Salerno"],
  "it-emr": ["Bologna", "Parma"],
  "it-laz": ["Rome", "Latina"],
  "it-lig": ["Genoa"],
  "it-lom": ["Milan", "Bergamo", "Brescia"],
  "it-pie": ["Turin"],
  "it-pug": ["Bari"],
  "it-sic": ["Palermo", "Catania"],
  "it-tus": ["Florence", "Pisa"],
  "it-ven": ["Venice", "Verona", "Padua"],
  "jm-ki": ["Kingston"],
  "jm-stc": ["Spanish Town", "Portmore"],
  "jm-sy": ["Montego Bay"],
  "jp-aichi": ["Nagoya"],
  "jp-chiba": ["Chiba"],
  "jp-fukuoka": ["Fukuoka", "Kitakyushu"],
  "jp-hokkaido": ["Sapporo", "Hakodate"],
  "jp-hyogo": ["Kobe", "Himeji"],
  "jp-kanagawa": ["Yokohama", "Kawasaki", "Sagamihara"],
  "jp-kyoto": ["Kyoto"],
  "jp-osaka": ["Osaka", "Sakai"],
  "jp-saitama": ["Saitama"],
  "jp-tokyo": ["Tokyo", "Shibuya", "Shinjuku", "Minato"],
  "ke-kiambu": ["Thika", "Ruiru", "Kikuyu"],
  "ke-kisumu": ["Kisumu"],
  "ke-machakos": ["Machakos", "Athi River"],
  "ke-mombasa": ["Mombasa", "Nyali", "Likoni"],
  "ke-nairobi": ["Nairobi", "Westlands", "Kasarani", "Embakaasi"],
  "ke-nakuru": ["Nakuru", "Naivasha"],
  "ke-uasin-gishu": ["Eldoret"],
  "kr-bs": ["Busan", "Haeundae"],
  "kr-dg": ["Daegu"],
  "kr-dj": ["Daejeon"],
  "kr-gg": ["Suwon", "Seongnam", "Goyang", "Yongin", "Bucheon"],
  "kr-gj": ["Gwangju"],
  "kr-ic": ["Incheon"],
  "kr-jj": ["Jeju City", "Seogwipo"],
  "kr-su": ["Seoul", "Gangnam", "Mapo", "Jongno"],
  "ma-cs": ["Casablanca", "Mohammedia", "El Jadida", "Settat"],
  "ma-fm": ["Fès", "Meknès"],
  "ma-ms": ["Marrakech", "Safi", "Essaouira"],
  "ma-or": ["Oujda", "Nador"],
  "ma-rs": ["Rabat", "Salé", "Kénitra", "Témara"],
  "ma-sm": ["Agadir", "Inezgane"],
  "ma-tn": ["Tangier", "Tétouan", "Al Hoceima"],
  "mx-bcn": ["Tijuana", "Mexicali"],
  "mx-cmx": ["Mexico City", "Coyoacán", "Polanco"],
  "mx-jal": ["Guadalajara", "Zapopan", "Puerto Vallarta"],
  "mx-nle": ["Monterrey", "San Pedro Garza García"],
  "mx-pue": ["Puebla"],
  "mx-roo": ["Cancún", "Playa del Carmen", "Tulum"],
  "mx-yuc": ["Mérida"],
  "nz-auk": ["Auckland", "Manukau", "North Shore"],
  "nz-bay": ["Tauranga", "Rotorua"],
  "nz-can": ["Christchurch"],
  "nz-ota": ["Dunedin", "Queenstown"],
  "nz-waik": ["Hamilton"],
  "nz-wgn": ["Wellington", "Lower Hutt"],
  "pe-are": ["Arequipa"],
  "pe-cal": ["Callao"],
  "pe-cus": ["Cusco"],
  "pe-lal": ["Trujillo"],
  "pe-lim": ["Lima", "Miraflores", "San Isidro", "Barranco"],
  "pe-piu": ["Piura"],
  "pg-mop": ["Lae"],
  "pg-ncd": ["Port Moresby"],
  "pl-ds": ["Wrocław"],
  "pl-ld": ["Łódź"],
  "pl-mp": ["Kraków", "Tarnów"],
  "pl-mz": ["Warsaw", "Radom", "Płock"],
  "pl-pm": ["Gdańsk", "Gdynia", "Sopot"],
  "pl-sl": ["Katowice", "Gliwice"],
  "pl-wp": ["Poznań"],
  "sa-as": ["Abha", "Khamis Mushait"],
  "sa-ea": ["Dammam", "Khobar", "Dhahran", "Al Ahsa", "Jubail"],
  "sa-jz": ["Jazan"],
  "sa-md": ["Medina", "Yanbu"],
  "sa-mk": ["Mecca", "Jeddah", "Taif"],
  "sa-ri": ["Riyadh", "Diriyah", "Al Kharj"],
  "sa-tb": ["Tabuk"],
  "sb-cap": ["Honiara"],
  "us-az": ["Phoenix", "Tucson"],
  "us-ca": ["Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento", "Oakland"],
  "us-co": ["Denver", "Boulder"],
  "us-dc": ["Washington"],
  "us-fl": ["Miami", "Orlando", "Tampa", "Jacksonville"],
  "us-ga": ["Atlanta"],
  "us-il": ["Chicago", "Aurora"],
  "us-ma": ["Boston", "Cambridge"],
  "us-mi": ["Detroit", "Ann Arbor"],
  "us-nv": ["Las Vegas", "Reno"],
  "us-ny": ["New York City", "Buffalo", "Rochester", "Albany"],
  "us-pa": ["Philadelphia", "Pittsburgh"],
  "us-tx": ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth"],
  "us-wa": ["Seattle", "Tacoma", "Spokane"],
  "ws-tu": ["Apia"],
  "za-ec": ["Gqeberha", "East London", "Mthatha"],
  "za-fs": ["Bloemfontein", "Welkom"],
  "za-gp": ["Johannesburg", "Pretoria", "Sandton", "Soweto", "Midrand", "Centurion"],
  "za-kzn": ["Durban", "Pietermaritzburg", "Richards Bay"],
  "za-lp": ["Polokwane"],
  "za-mp": ["Mbombela", "Witbank"],
  "za-nc": ["Kimberley", "Upington"],
  "za-nw": ["Rustenburg", "Mahikeng"],
  "za-wc": ["Cape Town", "Stellenbosch", "Paarl", "George"],
}
