/**
 * Nigeria — all 36 States + FCT, major LGAs and cities.
 * IDs: ng-{stateSlug}, ng-{stateSlug}-{lgaSlug}
 * Architecture supports adding remaining LGAs / wards without UI changes.
 */

export const NG_STATES: { id: string; name: string }[] = [
  { id: "ng-ab", name: "Abia" },
  { id: "ng-ad", name: "Adamawa" },
  { id: "ng-ak", name: "Akwa Ibom" },
  { id: "ng-an", name: "Anambra" },
  { id: "ng-ba", name: "Bauchi" },
  { id: "ng-by", name: "Bayelsa" },
  { id: "ng-be", name: "Benue" },
  { id: "ng-bo", name: "Borno" },
  { id: "ng-cr", name: "Cross River" },
  { id: "ng-de", name: "Delta" },
  { id: "ng-eb", name: "Ebonyi" },
  { id: "ng-ed", name: "Edo" },
  { id: "ng-ek", name: "Ekiti" },
  { id: "ng-en", name: "Enugu" },
  { id: "ng-fc", name: "FCT" },
  { id: "ng-go", name: "Gombe" },
  { id: "ng-im", name: "Imo" },
  { id: "ng-ji", name: "Jigawa" },
  { id: "ng-kd", name: "Kaduna" },
  { id: "ng-kn", name: "Kano" },
  { id: "ng-kt", name: "Katsina" },
  { id: "ng-ke", name: "Kebbi" },
  { id: "ng-ko", name: "Kogi" },
  { id: "ng-kw", name: "Kwara" },
  { id: "ng-la", name: "Lagos" },
  { id: "ng-na", name: "Nasarawa" },
  { id: "ng-ni", name: "Niger" },
  { id: "ng-og", name: "Ogun" },
  { id: "ng-on", name: "Ondo" },
  { id: "ng-os", name: "Osun" },
  { id: "ng-oy", name: "Oyo" },
  { id: "ng-pl", name: "Plateau" },
  { id: "ng-ri", name: "Rivers" },
  { id: "ng-so", name: "Sokoto" },
  { id: "ng-ta", name: "Taraba" },
  { id: "ng-yo", name: "Yobe" },
  { id: "ng-za", name: "Zamfara" },
]

/** Major LGAs / areas per state — expandable without redesign */
export const NG_LGAS: Record<string, string[]> = {
  "ng-ab": ["Aba North", "Aba South", "Arochukwu", "Bende", "Isiala Ngwa North", "Ohafia", "Umuahia North", "Umuahia South"],
  "ng-ad": ["Demsa", "Ganye", "Hong", "Jimeta", "Mubi North", "Numan", "Yola North", "Yola South"],
  "ng-ak": ["Eket", "Essien Udim", "Etinan", "Ikot Abasi", "Ikot Ekpene", "Oron", "Uyo", "Nsit Ubium"],
  "ng-an": ["Awka North", "Awka South", "Idemili North", "Idemili South", "Nnewi North", "Nnewi South", "Onitsha North", "Onitsha South"],
  "ng-ba": ["Alkaleri", "Bauchi", "Darazo", "Jama'are", "Katagum", "Misau", "Ningi", "Tafawa Balewa"],
  "ng-by": ["Brass", "Ekeremor", "Kolokuma/Opokuma", "Nembe", "Ogbia", "Sagbama", "Southern Ijaw", "Yenagoa"],
  "ng-be": ["Gboko", "Gwer East", "Katsina-Ala", "Konshisha", "Makurdi", "Otukpo", "Tarka", "Vandeikya"],
  "ng-bo": ["Askira/Uba", "Bama", "Biu", "Damboa", "Gwoza", "Jere", "Maiduguri", "Monguno"],
  "ng-cr": ["Akamkpa", "Akpabuyo", "Calabar Municipal", "Calabar South", "Ikom", "Odukpani", "Ogoja", "Yakurr"],
  "ng-de": ["Aniocha North", "Ethiope East", "Ika South", "Okpe", "Sapele", "Ughelli North", "Warri North", "Warri South"],
  "ng-eb": ["Abakaliki", "Afikpo North", "Afikpo South", "Ebonyi", "Ezza North", "Ishielu", "Ohaukwu", "Onicha"],
  "ng-ed": ["Akoko-Edo", "Egor", "Esan Central", "Oredo", "Orhionmwon", "Ovia North-East", "Owan East", "Uhunmwonde"],
  "ng-ek": ["Ado Ekiti", "Ekiti East", "Ekiti South-West", "Emure", "Ido Osi", "Ijero", "Ikere", "Irepodun/Ifelodun"],
  "ng-en": ["Enugu East", "Enugu North", "Enugu South", "Igbo-Etiti", "Nsukka", "Oji River", "Udi", "Udenu"],
  "ng-fc": ["Abaji", "Bwari", "Gwagwalada", "Kuje", "Kwali", "Municipal Area Council"],
  "ng-go": ["Akko", "Balanga", "Billiri", "Dukku", "Funakaye", "Gombe", "Kaltungo", "Yamaltu/Deba"],
  "ng-im": ["Aboh Mbaise", "Ehime Mbano", "Ideato North", "Mbaitoli", "Ngor Okpala", "Owerri Municipal", "Owerri North", "Orlu"],
  "ng-ji": ["Birnin Kudu", "Dutse", "Gumel", "Hadejia", "Kazaure", "Ringim", "Sule Tankarkar"],
  "ng-kd": ["Chikun", "Igabi", "Kaduna North", "Kaduna South", "Kagarko", "Kajuru", "Lere", "Zaria"],
  "ng-kn": ["Dala", "Fagge", "Gwale", "Kano Municipal", "Nassarawa", "Tarauni", "Ungogo", "Wudil"],
  "ng-kt": ["Daura", "Funtua", "Katsina", "Malumfashi", "Mani", "Musawa"],
  "ng-ke": ["Argungu", "Birnin Kebbi", "Jega", "Yauri", "Zuru"],
  "ng-ko": ["Ankpa", "Dekina", "Idah", "Kabba/Bunu", "Lokoja", "Okene"],
  "ng-kw": ["Asa", "Ilorin East", "Ilorin South", "Ilorin West", "Offa", "Oyun"],
  "ng-la": [
    "Agege", "Ajeromi-Ifelodun", "Alimosho", "Amuwo-Odofin", "Apapa", "Badagry", "Epe", "Eti-Osa",
    "Ibeju-Lekki", "Ifako-Ijaiye", "Ikeja", "Ikorodu", "Kosofe", "Lagos Island", "Lagos Mainland",
    "Mushin", "Ojo", "Oshodi-Isolo", "Shomolu", "Surulere",
  ],
  "ng-na": ["Akwanga", "Keffi", "Lafia", "Nasarawa", "Wamba"],
  "ng-ni": ["Bida", "Chanchaga", "Kontagora", "Minna", "Suleja"],
  "ng-og": ["Abeokuta North", "Abeokuta South", "Ado-Odo/Ota", "Ifo", "Ijebu Ode", "Sagamu", "Yewa South"],
  "ng-on": ["Akoko North-East", "Akure North", "Akure South", "Ondo East", "Ondo West", "Owo"],
  "ng-os": ["Ede North", "Ife Central", "Ilesa East", "Osogbo", "Iwo"],
  "ng-oy": ["Afijio", "Akinyele", "Ibadan North", "Ibadan North-East", "Ibadan North-West", "Ibadan South-East", "Ibadan South-West", "Ogbomosho North", "Oyo East"],
  "ng-pl": ["Barkin Ladi", "Bassa", "Jos East", "Jos North", "Jos South", "Pankshin", "Shendam"],
  "ng-ri": ["Bonny", "Eleme", "Ikwerre", "Obio/Akpor", "Okrika", "Port Harcourt"],
  "ng-so": ["Sokoto North", "Sokoto South", "Wamako", "Wurno"],
  "ng-ta": ["Jalingo", "Wukari", "Zing"],
  "ng-yo": ["Damaturu", "Nguru", "Potiskum"],
  "ng-za": ["Gusau", "Kaura Namoda", "Talata Mafara"],
}

/** Major cities/towns (locality) keyed by state — used when LGA not chosen or as shortcuts */
export const NG_CITIES: Record<string, string[]> = {
  "ng-la": ["Lagos", "Ikeja", "Lekki", "Victoria Island", "Surulere", "Ikorodu", "Badagry", "Epe"],
  "ng-fc": ["Abuja", "Gwarinpa", "Maitama", "Wuse", "Asokoro", "Kubwa", "Nyanya"],
  "ng-kn": ["Kano", "Nassarawa", "Fagge"],
  "ng-ri": ["Port Harcourt", "Obio-Akpor", "Eleme"],
  "ng-kd": ["Kaduna", "Zaria", "Kafanchan"],
  "ng-oy": ["Ibadan", "Ogbomosho", "Oyo"],
  "ng-og": ["Abeokuta", "Ijebu Ode", "Sango Ota"],
  "ng-an": ["Awka", "Onitsha", "Nnewi"],
  "ng-en": ["Enugu", "Nsukka"],
  "ng-ed": ["Benin City", "Auchi"],
  "ng-kw": ["Ilorin", "Offa"],
  "ng-pl": ["Jos"],
  "ng-be": ["Makurdi", "Gboko"],
  "ng-im": ["Owerri", "Orlu"],
  "ng-ak": ["Uyo", "Eket"],
  "ng-cr": ["Calabar", "Ikom"],
  "ng-de": ["Warri", "Asaba", "Sapele"],
  "ng-by": ["Yenagoa"],
  "ng-ad": ["Yola", "Mubi"],
  "ng-bo": ["Maiduguri"],
  "ng-so": ["Sokoto"],
  "ng-ba": ["Bauchi"],
  "ng-go": ["Gombe"],
  "ng-kt": ["Katsina", "Daura"],
  "ng-os": ["Osogbo", "Ile-Ife"],
  "ng-on": ["Akure", "Ondo"],
  "ng-ek": ["Ado Ekiti"],
  "ng-ab": ["Aba", "Umuahia"],
  "ng-eb": ["Abakaliki"],
  "ng-ni": ["Minna", "Suleja", "Bida"],
  "ng-na": ["Lafia", "Keffi"],
  "ng-ko": ["Lokoja", "Okene"],
  "ng-ke": ["Birnin Kebbi"],
  "ng-ji": ["Dutse", "Hadejia"],
  "ng-yo": ["Damaturu", "Potiskum"],
  "ng-za": ["Gusau"],
  "ng-ta": ["Jalingo"],
}
