/**
 * Nigeria — all 36 States + FCT.
 * LGAs aim for completeness (e.g. Kaduna = all 23). Cities include major towns;
 * LocationPicker always allows a custom city/town when not listed.
 * IDs: ng-{stateSlug}, ng-{stateSlug}-{lgaSlug}
 * Architecture supports adding remaining LGAs / wards without UI changes.
 */

export const NG_STATES: { id: string; name: string }[] = [
  { id: "ng-ab", name: "Abia" },
  { id: "ng-ad", name: "Adamawa" },
  { id: "ng-ak", name: "Akwa Ibom" },
  { id: "ng-an", name: "Anambra" },
  { id: "ng-ba", name: "Bauchi" },
  { id: "ng-by", name: "Bayelsa" },
  { id: "ng-be", name: "Benue" },
  { id: "ng-bo", name: "Borno" },
  { id: "ng-cr", name: "Cross River" },
  { id: "ng-de", name: "Delta" },
  { id: "ng-eb", name: "Ebonyi" },
  { id: "ng-ed", name: "Edo" },
  { id: "ng-ek", name: "Ekiti" },
  { id: "ng-en", name: "Enugu" },
  { id: "ng-fc", name: "FCT" },
  { id: "ng-go", name: "Gombe" },
  { id: "ng-im", name: "Imo" },
  { id: "ng-ji", name: "Jigawa" },
  { id: "ng-kd", name: "Kaduna" },
  { id: "ng-kn", name: "Kano" },
  { id: "ng-kt", name: "Katsina" },
  { id: "ng-ke", name: "Kebbi" },
  { id: "ng-ko", name: "Kogi" },
  { id: "ng-kw", name: "Kwara" },
  { id: "ng-la", name: "Lagos" },
  { id: "ng-na", name: "Nasarawa" },
  { id: "ng-ni", name: "Niger" },
  { id: "ng-og", name: "Ogun" },
  { id: "ng-on", name: "Ondo" },
  { id: "ng-os", name: "Osun" },
  { id: "ng-oy", name: "Oyo" },
  { id: "ng-pl", name: "Plateau" },
  { id: "ng-ri", name: "Rivers" },
  { id: "ng-so", name: "Sokoto" },
  { id: "ng-ta", name: "Taraba" },
  { id: "ng-yo", name: "Yobe" },
  { id: "ng-za", name: "Zamfara" },
]

/** Major LGAs / areas per state — expandable without redesign */

export const NG_LGAS: Record<string, string[]> = {
  "ng-ab": [
    "Aba North", "Aba South", "Arochukwu", "Bende", "Ikwuano", "Isiala Ngwa North",
    "Isiala Ngwa South", "Isuikwuato", "Obi Ngwa", "Ohafia", "Osisioma", "Ugwunagbo",
    "Ukwa East", "Ukwa West", "Umuahia North", "Umuahia South", "Umu Nneochi",
  ],
  "ng-ad": [
    "Demsa", "Fufore", "Ganye", "Girei", "Gombi", "Guyuk",
    "Hong", "Jada", "Lamurde", "Madagali", "Maiha", "Mayo-Belwa",
    "Michika", "Mubi North", "Mubi South", "Numan", "Shelleng", "Song",
    "Toungo", "Yola North", "Yola South",
  ],
  "ng-ak": [
    "Abak", "Eastern Obolo", "Eket", "Esit Eket", "Essien Udim", "Etim Ekpo",
    "Etinan", "Ibeno", "Ibesikpo Asutan", "Ibiono Ibom", "Ika", "Ikono",
    "Ikot Abasi", "Ikot Ekpene", "Ini", "Itu", "Mbo", "Mkpat Enin",
    "Nsit Atai", "Nsit Ibom", "Nsit Ubium", "Obot Akara", "Okobo", "Onna",
    "Oron", "Oruk Anam", "Udung Uko", "Ukanafun", "Uruan", "Urue-Offong/Oruko",
    "Uyo",
  ],
  "ng-an": [
    "Aguata", "Anambra East", "Anambra West", "Anaocha", "Awka North", "Awka South",
    "Ayamelum", "Dunukofia", "Ekwusigo", "Idemili North", "Idemili South", "Ihiala",
    "Njikoka", "Nnewi North", "Nnewi South", "Ogbaru", "Onitsha North", "Onitsha South",
    "Orumba North", "Orumba South", "Oyi",
  ],
  "ng-ba": [
    "Alkaleri", "Bauchi", "Bogoro", "Damban", "Darazo", "Dass",
    "Gamawa", "Ganjuwa", "Giade", "Itas/Gadau", "Jama'are", "Katagum",
    "Kirfi", "Misau", "Ningi", "Shira", "Tafawa Balewa", "Toro",
    "Warji", "Zaki",
  ],
  "ng-by": [
    "Brass", "Ekeremor", "Kolokuma/Opokuma", "Nembe", "Ogbia", "Sagbama",
    "Southern Ijaw", "Yenagoa",
  ],
  "ng-be": [
    "Ado", "Agatu", "Apa", "Buruku", "Gboko", "Guma",
    "Gwer East", "Gwer West", "Katsina-Ala", "Konshisha", "Kwande", "Logo",
    "Makurdi", "Obi", "Ogbadibo", "Ohimini", "Oju", "Okpokwu",
    "Oturkpo", "Tarka", "Ukum", "Ushongo", "Vandeikya",
  ],
  "ng-bo": [
    "Abadam", "Askira/Uba", "Bama", "Bayo", "Biu", "Chibok",
    "Damboa", "Dikwa", "Gubio", "Guzamala", "Gwoza", "Hawul",
    "Jere", "Kaga", "Kala/Balge", "Konduga", "Kukawa", "Kwaya Kusar",
    "Mafa", "Magumeri", "Maiduguri", "Marte", "Mobbar", "Monguno",
    "Ngala", "Nganzai", "Shani",
  ],
  "ng-cr": [
    "Abi", "Akamkpa", "Akpabuyo", "Bakassi", "Bekwarra", "Biase",
    "Boki", "Calabar Municipal", "Calabar South", "Etung", "Ikom", "Obanliku",
    "Obubra", "Obudu", "Odukpani", "Ogoja", "Yakuur", "Yala",
  ],
  "ng-de": [
    "Aniocha North", "Aniocha South", "Bomadi", "Burutu", "Ethiope East", "Ethiope West",
    "Ika North East", "Ika South", "Isoko North", "Isoko South", "Ndokwa East", "Ndokwa West",
    "Okpe", "Oshimili North", "Oshimili South", "Patani", "Sapele", "Udu",
    "Ughelli North", "Ughelli South", "Ukwuani", "Uvwie", "Warri North", "Warri South",
    "Warri South West",
  ],
  "ng-eb": [
    "Abakaliki", "Afikpo North", "Afikpo South", "Ebonyi", "Ezza North", "Ezza South",
    "Ikwo", "Ishielu", "Ivo", "Izzi", "Ohaozara", "Ohaukwu",
    "Onicha",
  ],
  "ng-ed": [
    "Akoko-Edo", "Egor", "Esan Central", "Esan North-East", "Esan South-East", "Esan West",
    "Etsako Central", "Etsako East", "Etsako West", "Igueben", "Ikpoba-Okha", "Oredo",
    "Orhionmwon", "Ovia North-East", "Ovia South-West", "Owan East", "Owan West", "Uhunmwonde",
  ],
  "ng-ek": [
    "Ado Ekiti", "Efon", "Ekiti East", "Ekiti South-West", "Ekiti West", "Emure",
    "Gbonyin", "Ido Osi", "Ijero", "Ikere", "Ikole", "Ilejemeje",
    "Irepodun/Ifelodun", "Ise/Orun", "Moba", "Oye",
  ],
  "ng-en": [
    "Aninri", "Awgu", "Enugu East", "Enugu North", "Enugu South", "Ezeagu",
    "Igbo Etiti", "Igbo Eze North", "Igbo Eze South", "Isi Uzo", "Nkanu East", "Nkanu West",
    "Nsukka", "Oji River", "Udenu", "Udi", "Uzo Uwani",
  ],
  "ng-go": [
    "Akko", "Balanga", "Billiri", "Dukku", "Funakaye", "Gombe",
    "Kaltungo", "Kwami", "Nafada", "Shongom", "Yamaltu/Deba",
  ],
  "ng-im": [
    "Aboh Mbaise", "Ahiazu Mbaise", "Ehime Mbano", "Ezinihitte", "Ideato North", "Ideato South",
    "Ihitte/Uboma", "Ikeduru", "Isiala Mbano", "Isu", "Mbaitoli", "Ngor Okpala",
    "Njaba", "Nkwerre", "Nwangele", "Obowo", "Oguta", "Ohaji/Egbema",
    "Okigwe", "Onuimo", "Orlu", "Orsu", "Oru East", "Oru West",
    "Owerri Municipal", "Owerri North", "Owerri West",
  ],
  "ng-ji": [
    "Auyo", "Babura", "Biriniwa", "Birnin Kudu", "Buji", "Dutse",
    "Gagarawa", "Garki", "Gumel", "Guri", "Gwaram", "Gwiwa",
    "Hadejia", "Jahun", "Kafin Hausa", "Kaugama", "Kazaure", "Kiri Kasama",
    "Kiyawa", "Maigatari", "Malam Madori", "Miga", "Ringim", "Roni",
    "Sule Tankarkar", "Taura", "Yankwashi",
  ],
  "ng-kd": [
    "Birnin Gwari", "Chikun", "Giwa", "Igabi", "Ikara", "Jaba",
    "Jema'a", "Kachia", "Kaduna North", "Kaduna South", "Kagarko", "Kajuru",
    "Kaura", "Kauru", "Kubau", "Kudan", "Lere", "Makarfi",
    "Sabon Gari", "Sanga", "Soba", "Zangon Kataf", "Zaria",
  ],
  "ng-kn": [
    "Ajingi", "Albasu", "Bagwai", "Bebeji", "Bichi", "Bunkure",
    "Dala", "Dambatta", "Dawakin Kudu", "Dawakin Tofa", "Doguwa", "Fagge",
    "Gabasawa", "Garko", "Garun Mallam", "Gaya", "Gezawa", "Gwale",
    "Gwarzo", "Kabo", "Kano Municipal", "Karaye", "Kibiya", "Kiru",
    "Kumbotso", "Kunchi", "Kura", "Madobi", "Makoda", "Minjibir",
    "Nasarawa", "Rano", "Rimin Gado", "Rogo", "Shanono", "Sumaila",
    "Takai", "Tarauni", "Tofa", "Tsanyawa", "Tudun Wada", "Ungogo",
    "Warawa", "Wudil",
  ],
  "ng-kt": [
    "Bakori", "Batagarawa", "Batsari", "Baure", "Bindawa", "Charanchi",
    "Dandume", "Danja", "Dan Musa", "Daura", "Dutsi", "Dutsin-Ma",
    "Faskari", "Funtua", "Ingawa", "Jibia", "Kafur", "Kaita",
    "Kankara", "Kankia", "Katsina", "Kurfi", "Kusada", "Mai'Adua",
    "Malumfashi", "Mani", "Mashi", "Matazu", "Musawa", "Rimi",
    "Sabuwa", "Safana", "Sandamu", "Zango",
  ],
  "ng-ke": [
    "Aleiro", "Arewa Dandi", "Argungu", "Augie", "Bagudo", "Birnin Kebbi",
    "Bunza", "Dandi", "Fakai", "Gwandu", "Jega", "Kalgo",
    "Koko/Besse", "Maiyama", "Ngaski", "Sakaba", "Shanga", "Suru",
    "Wasagu/Danko", "Yauri", "Zuru",
  ],
  "ng-ko": [
    "Adavi", "Ajaokuta", "Ankpa", "Bassa", "Dekina", "Ibaji",
    "Idah", "Igalamela-Odolu", "Ijumu", "Kabba/Bunu", "Kogi", "Lokoja",
    "Mopa-Muro", "Ofu", "Ogori/Magongo", "Okehi", "Okene", "Olamaboro",
    "Omala", "Yagba East", "Yagba West",
  ],
  "ng-kw": [
    "Asa", "Baruten", "Edu", "Ekiti", "Ifelodun", "Ilorin East",
    "Ilorin South", "Ilorin West", "Irepodun", "Isin", "Kaiama", "Moro",
    "Offa", "Oke Ero", "Oyun", "Pategi",
  ],
  "ng-la": [
    "Agege", "Ajeromi-Ifelodun", "Alimosho", "Amuwo-Odofin", "Apapa", "Badagry",
    "Epe", "Eti-Osa", "Ibeju-Lekki", "Ifako-Ijaiye", "Ikeja", "Ikorodu",
    "Kosofe", "Lagos Island", "Lagos Mainland", "Mushin", "Ojo", "Oshodi-Isolo",
    "Shomolu", "Surulere",
  ],
  "ng-na": [
    "Akwanga", "Awe", "Doma", "Karu", "Keana", "Keffi",
    "Kokona", "Lafia", "Nasarawa", "Nasarawa Eggon", "Obi", "Toto",
    "Wamba",
  ],
  "ng-ni": [
    "Agaie", "Agwara", "Bida", "Borgu", "Bosso", "Chanchaga",
    "Edati", "Gbako", "Gurara", "Katcha", "Kontagora", "Lapai",
    "Lavun", "Magama", "Mariga", "Mashegu", "Mokwa", "Moya",
    "Paikoro", "Rafi", "Rijau", "Shiroro", "Suleja", "Tafa",
    "Wushishi",
  ],
  "ng-og": [
    "Abeokuta North", "Abeokuta South", "Ado-Odo/Ota", "Egbado North", "Egbado South", "Ewekoro",
    "Ifo", "Ijebu East", "Ijebu North", "Ijebu North East", "Ijebu Ode", "Ikenne",
    "Imeko Afon", "Ipokia", "Obafemi Owode", "Odeda", "Odogbolu", "Ogun Waterside",
    "Remo North", "Shagamu",
  ],
  "ng-on": [
    "Akoko North-East", "Akoko North-West", "Akoko South-East", "Akoko South-West", "Akure North", "Akure South",
    "Ese-Odo", "Idanre", "Ifedore", "Ilaje", "Ile Oluji/Okeigbo", "Irele",
    "Odigbo", "Okitipupa", "Ondo East", "Ondo West", "Ose", "Owo",
  ],
  "ng-os": [
    "Atakunmosa East", "Atakunmosa West", "Aiyedaade", "Aiyedire", "Boluwaduro", "Boripe",
    "Ede North", "Ede South", "Egbedore", "Ejigbo", "Ife Central", "Ife East",
    "Ife North", "Ife South", "Ifedayo", "Ifelodun", "Ila", "Ilesa East",
    "Ilesa West", "Irepodun", "Irewole", "Isokan", "Iwo", "Obokun",
    "Odo Otin", "Ola Oluwa", "Olorunda", "Oriade", "Orolu", "Osogbo",
  ],
  "ng-oy": [
    "Afijio", "Akinyele", "Atiba", "Atisbo", "Egbeda", "Ibadan North",
    "Ibadan North-East", "Ibadan North-West", "Ibadan South-East", "Ibadan South-West", "Ibarapa Central", "Ibarapa East",
    "Ibarapa North", "Ido", "Irepo", "Iseyin", "Itesiwaju", "Iwajowa",
    "Kajola", "Lagelu", "Ogbomosho North", "Ogbomosho South", "Ogo Oluwa", "Olorunsogo",
    "Oluyole", "Ona Ara", "Orelope", "Ori Ire", "Oyo East", "Oyo West",
    "Saki East", "Saki West", "Surulere",
  ],
  "ng-pl": [
    "Barkin Ladi", "Bassa", "Bokkos", "Jos East", "Jos North", "Jos South",
    "Kanam", "Kanke", "Langtang North", "Langtang South", "Mangu", "Mikang",
    "Pankshin", "Qua'an Pan", "Riyom", "Shendam", "Wase",
  ],
  "ng-ri": [
    "Abua/Odual", "Ahoada East", "Ahoada West", "Akuku-Toru", "Andoni", "Asari-Toru",
    "Bonny", "Degema", "Eleme", "Emohua", "Etche", "Gokana",
    "Ikwerre", "Khana", "Obio/Akpor", "Ogba/Egbema/Ndoni", "Ogu/Bolo", "Okrika",
    "Omuma", "Opobo/Nkoro", "Oyigbo", "Port Harcourt", "Tai",
  ],
  "ng-so": [
    "Binji", "Bodinga", "Dange Shuni", "Gada", "Goronyo", "Gudu",
    "Gwadabawa", "Illela", "Isa", "Kebbe", "Kware", "Rabah",
    "Sabon Birni", "Shagari", "Silame", "Sokoto North", "Sokoto South", "Tambuwal",
    "Tangaza", "Tureta", "Wamako", "Wurno", "Yabo",
  ],
  "ng-ta": [
    "Ardo-Kola", "Bali", "Donga", "Gashaka", "Gassol", "Ibi",
    "Jalingo", "Karim Lamido", "Kurmi", "Lau", "Sardauna", "Takum",
    "Ussa", "Wukari", "Yorro", "Zing",
  ],
  "ng-yo": [
    "Bade", "Bursari", "Damaturu", "Fika", "Fune", "Geidam",
    "Gujba", "Gulani", "Jakusko", "Karasuwa", "Machina", "Nangere",
    "Nguru", "Potiskum", "Tarmuwa", "Yunusari", "Yusufari",
  ],
  "ng-za": [
    "Anka", "Bakura", "Birnin Magaji/Kiyaw", "Bukkuyum", "Bungudu", "Gummi",
    "Gusau", "Kaura Namoda", "Maradun", "Maru", "Shinkafi", "Talata Mafara",
    "Tsafe", "Zurmi",
  ],
  "ng-fc": [
    "Abaji", "Bwari", "Gwagwalada", "Kuje", "Kwali", "Municipal Area Council",
  ],
}

export const NG_CITIES: Record<string, string[]> = {
  "ng-la": ["Lagos", "Ikeja", "Lekki", "Victoria Island", "Surulere", "Yaba", "Ikorodu", "Badagry", "Epe", "Ajah"],
  "ng-fc": ["Abuja", "Gwagwalada", "Kuje", "Bwari", "Kubwa", "Lugbe", "Nyanya"],
  "ng-ri": ["Port Harcourt", "Obio-Akpor", "Eleme", "Bonny", "Okrika", "Ahoada"],
  "ng-kd": ["Kaduna", "Zaria", "Kafanchan", "Kachia", "Zonkwa", "Birnin Gwari", "Kagoro", "Saminaka", "Makarfi", "Manchok", "Fadan Karshi", "Kwoi", "Kajuru", "Kagoma"],
  "ng-kn": ["Kano", "Nassarawa", "Fagge", "Dala", "Gwale", "Tarauni", "Ungogo", "Wudil", "Bichi"],
  "ng-oy": ["Ibadan", "Ogbomosho", "Oyo", "Iseyin", "Saki", "Eruwa"],
  "ng-og": ["Abeokuta", "Ijebu Ode", "Sango Ota", "Sagamu", "Ilaro"],
  "ng-an": ["Awka", "Onitsha", "Nnewi", "Ekwulobia"],
  "ng-en": ["Enugu", "Nsukka", "Oji River", "Awgu"],
  "ng-ed": ["Benin City", "Auchi", "Ekpoma", "Uromi"],
  "ng-kw": ["Ilorin", "Offa", "Jebba"],
  "ng-pl": ["Jos", "Bukuru", "Pankshin", "Shendam"],
  "ng-be": ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala"],
  "ng-im": ["Owerri", "Orlu", "Okigwe"],
  "ng-ak": ["Uyo", "Eket", "Ikot Ekpene", "Oron"],
  "ng-cr": ["Calabar", "Ikom", "Ogoja"],
  "ng-de": ["Warri", "Asaba", "Sapele", "Ughelli", "Agbor"],
  "ng-by": ["Yenagoa"],
  "ng-ad": ["Yola", "Mubi"],
  "ng-bo": ["Maiduguri", "Biu", "Bama"],
  "ng-so": ["Sokoto", "Wamako", "Tambuwal"],
  "ng-ba": ["Bauchi", "Azare", "Jama'are"],
  "ng-go": ["Gombe", "Billiri", "Kaltungo"],
  "ng-kt": ["Katsina", "Daura", "Funtua"],
  "ng-os": ["Osogbo", "Ile-Ife", "Ilesa", "Iwo"],
  "ng-on": ["Akure", "Ondo", "Owo", "Okitipupa"],
  "ng-ek": ["Ado Ekiti", "Ikere", "Ijero"],
  "ng-ab": ["Aba", "Umuahia", "Arochukwu"],
  "ng-eb": ["Abakaliki", "Afikpo"],
  "ng-ni": ["Minna", "Suleja", "Bida", "Kontagora"],
  "ng-na": ["Lafia", "Keffi", "Akwanga"],
  "ng-ko": ["Lokoja", "Okene", "Kabba", "Idah"],
  "ng-ke": ["Birnin Kebbi", "Argungu", "Yauri", "Zuru"],
  "ng-ji": ["Dutse", "Hadejia", "Birnin Kudu"],
  "ng-yo": ["Damaturu", "Potiskum", "Nguru", "Geidam"],
  "ng-za": ["Gusau", "Kaura Namoda", "Talata Mafara"],
  "ng-ta": ["Jalingo", "Wukari", "Takum", "Bali"],
}
